# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oxgg-wgnsVhDhqvoDxqWMIDZtbloET_S
"""

!pip install streamlit
import streamlit as st
import joblib
import numpy as np

# Configuración de la página
st.set_page_config(
    page_title="Forecasting MP2.5 - Las Encinas",
    page_icon="🌫️",
    layout="centered"
)

# Título
st.title("🌫️ Forecasting MP2.5 – Estación Las Encinas, Temuco")
st.markdown("---")
st.markdown("*Ingresa los valores para predecir la concentración horaria de MP2.5:*")

# Cargar el modelo
@st.cache_resource
def cargar_modelo():
    try:
        model = joblib.load('modelo_forecasting_mp25_xgb.pkl')
        return model
    except:
        st.error("❌ No se encontró el archivo del modelo.")
        return None

model = cargar_modelo()

if model is not None:
    # --- Formulario de entrada ---
    with st.form("prediccion_form"):
        col1, col2 = st.columns(2)

        with col1:
            hora = st.number_input("🕐 HORA (0-23)", min_value=0, max_value=23, value=20, step=1)
            dia_semana = st.number_input("📅 DÍA_SEMANA (0=Lunes, 6=Domingo)", min_value=0, max_value=6, value=2, step=1)
            mes = st.number_input("📆 MES (1-12)", min_value=1, max_value=12, value=7, step=1)

        with col2:
            lag_1 = st.number_input("🔄 LAG_1 (hora anterior en µg/m³)", min_value=0.0, value=45.2, step=1.0)
            lag_24 = st.number_input("🔄 LAG_24 (misma hora día anterior en µg/m³)", min_value=0.0, value=38.7, step=1.0)

        submitted = st.form_submit_button("🔮 Predecir MP2.5", use_container_width=True)

    # --- Predicción ---
    if submitted and model is not None:
        input_data = np.array([[hora, dia_semana, mes, lag_1, lag_24]])
        pred = model.predict(input_data)[0]

        st.markdown("---")
        st.subheader("📊 Resultado de la Predicción")
        st.metric("Concentración estimada de MP2.5", f"{pred:.2f} µg/m³")

        if pred < 50:
            st.success("✅ *Nivel bajo:* Aire saludable.")
        elif pred < 100:
            st.warning("⚠️ *Nivel moderado:* Precaución para grupos sensibles.")
        else:
            st.error("🚨 *Nivel alto:* Episodio crítico. ¡Activar alerta!")

st.markdown("---")
st.caption("Proyecto Minería de Datos - Universidad Bernardo O'Higgins")